version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
s3_prefix = "serverless-ghost"
capabilities = "CAPABILITY_IAM"
region = "af-south-1"
parameter_overrides = "DomainName=\"blog.hacksaw.co.za\" EnableDebugLogs=\"true\" EnableNat=\"true\" UseServerlessDb=\"true\" SentryDsn=\"\" SesSmtpPassword=\"\""